using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Linq;
using Content.Client.Stylesheets.Fonts;
using Content.Client.Stylesheets.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI;

/// <summary>
/// Allows users to select a font from their system fonts, along with a scale for it. Displays a preview.
/// </summary>
/// <seealso cref="OptionFontScaleCVar"/>
/// <seealso cref="OptionFontFamilyNameCVar"/>
[GenerateTypedNameReferences]
public sealed partial class OptionFontSelector : Control
{
    private const int IdDefault = -1;
    private const int IdMissing = -2;

    private const int DefaultFontSize = NanotrasenStylesheet.PrimaryFontSize;

    private static readonly float[] ScaleValues =
    [
        0.75f,
        1,
        1.25f,
        1.5f,
        1.75f,
        2.0f,
        2.25f,
        2.5f,
        2.75f,
        3.0f,
    ];

    [Dependency] private ISystemFontManager _systemFontManager = null!;
    [Dependency] private IFontSelectionManager _fontSelection = null!;

    private readonly List<AvailableFont> _availableFonts = new();

    private string? _familyName;
    private bool _hasMissingFontEntry;
    private float _scale;

    public StandardFontType StandardType { get; set; }

    /// <summary>
    /// The text describing what this selector affects.
    /// </summary>
    public string Title
    {
        set => TitleLabel.Text = value;
    }

    /// <summary>
    /// The global scale that has been selected.
    /// </summary>
    public float Scale
    {
        get => _scale;
        set
        {
            _scale = value;
            // Select closest value. In case the user modified their CVars directly.
            ScaleDropDown.SelectId(ScaleValues.Index().MinBy(t => Math.Abs(t.Item - _scale)).Index);
            UpdatePreview();
        }
    }

    /// <summary>
    /// The family name, in the user's system fonts, that has been selected.
    /// </summary>
    public string? FamilyName
    {
        get => _familyName;
        set
        {
            _familyName = value;
            UpdateFontSelection();
            UpdatePreview();
        }
    }

    /// <summary>
    /// Raised when the user changed the selected <see cref="Scale"/>.
    /// </summary>
    public event Action? OnScaleChanged;

    /// <summary>
    /// Raised when the user changed the selected <see cref="FamilyName"/>.
    /// </summary>
    public event Action? OnFamilyNameChanged;

    public OptionFontSelector()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        DropDown.AddItem(Loc.GetString("ui-options-font-selector-default"), IdDefault);

        var faces = _systemFontManager.SystemFontFaces.GroupBy(s =>
            s.GetLocalizedFamilyName(CultureInfo.InvariantCulture));

        foreach (var family in faces)
        {
            var familyName = family.Key;
            var familyFaces = family.ToArray();

            var familyNameLocalized = familyFaces[0].FamilyName;

            _availableFonts.Add(new AvailableFont
            {
                Faces = familyFaces,
                FamilyName = familyName,
                FamilyNameLocalized = familyNameLocalized,
            });
        }

        _availableFonts.Sort((a, b) => string.Compare(
            a.FamilyNameLocalized,
            b.FamilyNameLocalized,
            StringComparison.CurrentCultureIgnoreCase));

        for (var i = 0; i < _availableFonts.Count; i++)
        {
            var available = _availableFonts[i];
            DropDown.AddItem(available.FamilyNameLocalized, i);
        }

        DropDown.OnItemSelected += ie =>
        {
            _familyName = ie.Id switch
            {
                IdDefault => null,
                IdMissing => _familyName,
                _ => _availableFonts[ie.Id].FamilyName,
            };

            UpdateFontSelection();
            UpdatePreview();
            OnFamilyNameChanged?.Invoke();
        };

        for (var i = 0; i < ScaleValues.Length; i++)
        {
            var scale = ScaleValues[i];
            ScaleDropDown.AddItem(scale.ToString("P0"), i);
        }

        ScaleDropDown.OnItemSelected += ie =>
        {
            ScaleDropDown.SelectId(ie.Id);
            _scale = ScaleValues[ie.Id];
            UpdatePreview();
            OnScaleChanged?.Invoke();
        };
    }

    protected override void EnteredTree()
    {
    }

    protected override void ExitedTree()
    {
    }

    private void UpdatePreview()
    {
        Font font;
        var scaleFontSize = _fontSelection.ScaleFontSize(_scale, DefaultFontSize);

        if (_familyName != null && TryGetAvailableFont(_familyName, out var available))
        {
            font = SelectOptimalDefault(available.Faces).Load(scaleFontSize);
        }
        else
        {
            font = _fontSelection.GetDefaultFont(StandardType, scaleFontSize);
        }

        PreviewLabel.FontOverride = font;
    }

    private static ISystemFontFace SelectOptimalDefault(ISystemFontFace[] options)
    {
        // Default params are all regular.
        return FontSelectionHelpers.SelectClosest(options);
    }

    private void UpdateFontSelection()
    {
        RemoveMissingFontEntry();

        if (_familyName == null)
        {
            DropDown.SelectId(IdDefault);
            return;
        }

        if (!TryGetAvailableFont(_familyName, out var available))
        {
            DropDown.AddItem(Loc.GetString("ui-options-font-selector-missing", ("fontName", _familyName)), IdMissing);
            _hasMissingFontEntry = true;
            DropDown.SelectId(IdMissing);
            return;
        }

        DropDown.SelectId(_availableFonts.IndexOf(available));
    }

    private bool TryGetAvailableFont(string familyName, [NotNullWhen(true)] out AvailableFont? available)
    {
        foreach (var font in _availableFonts)
        {
            if (font.FamilyName != familyName)
                continue;

            available = font;
            return true;
        }

        available = null;
        return false;
    }

    private void RemoveMissingFontEntry()
    {
        if (!_hasMissingFontEntry)
            return;

        DropDown.RemoveItem(DropDown.GetIdx(IdMissing));
        _hasMissingFontEntry = false;
    }

    private sealed class AvailableFont
    {
        public required string FamilyName;
        public required string FamilyNameLocalized;
        public required ISystemFontFace[] Faces;
    }
}
