using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls.Redux;

[GenerateTypedNameReferences]
public sealed partial class Checkbox : Control
{
    public Checkbox()
    {
        RobustXamlLoader.Load(this);
    }
}

