using Avalonia.Metadata;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls.Redux;

[GenerateTypedNameReferences]
public sealed partial class Tabs : Control
{
    // Button group?

    private BoxContainer _rootContainer;
    private BoxContainer _contentContainer;
    private BoxContainer _buttonContainer;

    public Tabs()
    {
        RobustXamlLoader.Load(this);

        _rootContainer = new BoxContainer();

        _buttonContainer = new BoxContainer();
        _rootContainer.AddChild(_buttonContainer);

        _contentContainer = new BoxContainer();
        _rootContainer.AddChild(_contentContainer);

        XamlChildren = _contentContainer.Children;

        foreach (var child in Children)
        {
            if (child is Tab t)
            {
                var btn = new Button
                {
                    Text = t.Key,
                };

                _buttonContainer.AddChild(btn);
            }
        }
    }

    // CurrentTab
    // SetTab
    // On Tab Changed

    // <tabs>
    //   <tab Key="Test">
    //     <Label Title="Hi" />
    //   </tab>
    //   <tab Key="Huh">
    //     <Label Title="Bye" />
    //   </tab>
    // </tabs>

    public sealed partial class Tab : Container
    {
        // Tab title
        // Tab content

        public string? Key { get; set; }

        public Tab()
        {
        }
    }
}
