using Avalonia.Metadata;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Controls.Redux;

public sealed partial class Tabs : BoxContainer
{
    // Button group?

    private BoxContainer _contentContainer;
    private BoxContainer _buttonContainer;

    public Tabs()
    {
        _buttonContainer = new BoxContainer();
        AddChild(_buttonContainer);

        _contentContainer = new BoxContainer { VerticalExpand = true };
        AddChild(_contentContainer);

        XamlChildren = _contentContainer.Children;

        foreach (var child in Children)
        {
            if (child is not Tab t)
                continue;

            var btn = new Button
            {
                Text = t.Key,
            };

            _buttonContainer.AddChild(btn);
        }
    }

    // CurrentTab
    // SetTab
    // On Tab Changed

    // <tabs>
    //   <tab Key="Test">
    //     <Label Title="Hi" />
    //   </tab>
    //   <tab Key="Huh">
    //     <Label Title="Bye" />
    //   </tab>
    // </tabs>
}

public sealed partial class Tab : BoxContainer
{
    // Tab title
    // Tab content

    public string? Key { get; set; }
    public string? Title { get; set; }

    public Tab()
    {
        VerticalExpand = true;
    }
}
