using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Controls.Redux;

/// <summary>
/// Base window for all SS14 windows.
/// </summary>
[GenerateTypedNameReferences]
[Virtual]
public partial class Window : BaseWindow
{
    /// <summary>
    /// This ensures that windows are always visible on screen and don't become unreachable. This only applies
    /// if the window is allowed to be partially off-screen.
    /// </summary>
    public float WindowEdgeSeparation = 30;

    /// <summary>
    /// If a window is completely off-screen, the window will be bumped away from the edge so that its not a
    /// tiny square hidden in a corner. Effectively a conditional increase to <see cref="WindowEdgeSeparation"/>.
    /// Helpful when changing UI scale or changing the window size.
    /// </summary>
    public float WindowEdgeBump = 50;

    /// <summary>
    /// How far into the window should it allow to drag and resize the window.
    /// </summary>
    public const int DragMarginSize = 7;

    /// <summary>
    /// This option determines whether a window is allowed to be dragged off the edge of the screen (as long as
    /// part of it remains visible).
    /// </summary>
    /// <remarks>
    /// Note that you generally want to disable north, as that will mean the header might not be visible, which
    /// might cause the window to be unmovable.
    /// </remarks>
    public DirectionFlag AllowOffScreen = ~DirectionFlag.North;

    private string? _headerClass;
    private string? _titleClass;

    #region Style Classes

    public const string StyleClassWindowTitle = "WindowTitle";
    public const string StyleClassWindowPanel = "WindowPanel";
    public const string StyleClassWindowHeader = "WindowHeader";
    public const string StyleClassWindowCloseButton = "WindowCloseButton";

    #endregion

    public Window()
    {
        RobustXamlLoader.Load(this);

        CloseButton.OnPressed += _ => Close();
        XamlChildren = ContentsContainer.Children;
    }

    /// <summary>
    /// The title displayed on the window.
    /// </summary>
    /// <remarks>Defaults to {Loc 'window-title-placeholder'}</remarks>
    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    /// <summary>
    /// The class which the Header's panel container uses.
    /// </summary>
    /// <remarks>Defaults to 'WindowHeader'/></remarks>
    public string? HeaderClass
    {
        get => _headerClass;
        set
        {
            if (_headerClass == value)
                return;

            if (_headerClass != null)
                HeaderPanel.RemoveStyleClass(_headerClass);

            if (value != null)
                HeaderPanel.AddStyleClass(value);

            _headerClass = value;
        }
    }

    /// <summary>
    /// The class which the Title's label uses.
    /// </summary>
    /// <remarks>Defaults to 'WindowTitle'/></remarks>
    public string? TitleClass
    {
        get => _titleClass;
        set
        {
            if (_titleClass == value)
                return;

            if (_titleClass != null)
                TitleLabel.RemoveStyleClass(_titleClass);

            if (value != null)
                TitleLabel.AddStyleClass(value);

            _titleClass = value;
        }
    }

    /// <summary>
    /// A modified FrameUpdate to ensure that the window's header always stays on screen.
    /// </summary>
    protected override void FrameUpdate(FrameEventArgs args)
    {
        var (spaceX, spaceY) = Parent!.Size;

        var maxX = spaceX - ((AllowOffScreen & DirectionFlag.West) == 0 ? Size.X : WindowEdgeSeparation);
        var maxY = spaceY - ((AllowOffScreen & DirectionFlag.South) == 0 ? Size.Y : WindowEdgeSeparation);

        if (Position.X > spaceX)
            maxX -= WindowEdgeBump;

        if (Position.Y > spaceY)
            maxY -= WindowEdgeBump;

        var pos = Vector2.Min(Position, new Vector2(maxX, maxY));

        var minX = (AllowOffScreen & DirectionFlag.East) == 0 ? 0 : WindowEdgeSeparation - Size.X;
        var minY = (AllowOffScreen & DirectionFlag.North) == 0 ? 0 : WindowEdgeSeparation - Size.Y;

        pos = Vector2.Max(pos, new Vector2(minX, minY));
        if (Position != pos)
            LayoutContainer.SetPosition(this, pos);
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        var mode = DragMode.Move;

        if (!Resizable)
            return mode;

        if (relativeMousePos.Y < DragMarginSize)
        {
            mode = DragMode.Top;
        }
        else if (relativeMousePos.Y > Size.Y - DragMarginSize)
        {
            mode = DragMode.Bottom;
        }

        if (relativeMousePos.X < DragMarginSize)
        {
            mode |= DragMode.Left;
        }
        else if (relativeMousePos.X > Size.X - DragMarginSize)
        {
            mode |= DragMode.Right;
        }

        return mode;
    }
}
