using System.Linq;
using Content.Client.Construction;
using Content.Client.UserInterface.Controls;
using Content.Shared.Construction.Prototypes;
using Content.Shared.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Systems.Construction.Windows;

[GenerateTypedNameReferences]
public sealed partial class ConstructionWindow : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _systemManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly ConstructionSystem _constructionSystem;
    private readonly EntityWhitelistSystem _whitelistSystem;

    private ConstructionPrototype? _selection;

    private readonly List<string> _categories;

    private const string FavoriteCategory = "construction-category-favorites";
    private const string AllCategory = "construction-category-all";

    public ConstructionWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _constructionSystem = _systemManager.GetEntitySystem<ConstructionSystem>();
        _spriteSystem = _systemManager.GetEntitySystem<SpriteSystem>();
        _whitelistSystem = _systemManager.GetEntitySystem<EntityWhitelistSystem>();

        _categories = GetCategories();

        BuildButton.OnToggled += Build;
        EraseButton.OnToggled += Erase;

        Recipes.OnItemSelected += SelectRecipe;
        Recipes.OnItemDeselected += _ => DeselectRecipe();

        FavoriteButton.OnPressed += _ => _constructionSystem.ToggleFavorite(_selection);

        SearchBar.OnTextChanged += _ => PopulateRecipes(SearchBar.Text, _categories[OptionCategories.SelectedId]);
        OptionCategories.OnItemSelected += HandleSetCategory;

        ClearButton.OnPressed += _ => _constructionSystem.ClearAllGhosts();

        _constructionSystem.PlacementChanged += (_, _) => DisableAll();

        PopulateCategories();
        PopulateRecipes(string.Empty, AllCategory);
    }

    private void HandleSetCategory(OptionButton.ItemSelectedEventArgs args)
    {
        OptionCategories.SelectId(args.Id);
        SearchBar.SetText(string.Empty);
        PopulateRecipes(string.Empty, _categories[args.Id]);
    }

    private List<string> GetCategories()
    {
        var categories = new HashSet<string>();

        foreach (var prototype in _prototypeManager.EnumeratePrototypes<ConstructionPrototype>())
        {
            var category = prototype.Category;

            if (!string.IsNullOrEmpty(category))
                categories.Add(category);
        }

        categories.Add(FavoriteCategory);
        categories.Add(AllCategory);

        return categories.OrderBy(Loc.GetString).ToList();
    }

    private void PopulateCategories()
    {
        OptionCategories.Clear();

        foreach (var category in _categories)
        {
            OptionCategories.AddItem(Loc.GetString(category));
        }
    }

    private void PopulateRecipes(string search, string category)
    {
        var recipes = new List<ConstructionPrototype>();

        Recipes.Clear();

        foreach (var recipe in _prototypeManager.EnumeratePrototypes<ConstructionPrototype>())
        {
            // Skip hidden recipes (e.g. mirrored recipes)
            if (recipe.Hide)
                continue;

            // Skip entity-locked recipes (e.g. arachnid's web buildings)
            if (_playerManager.LocalSession == null
                || _playerManager.LocalEntity == null
                || _whitelistSystem.IsWhitelistFail(recipe.EntityWhitelist, _playerManager.LocalEntity.Value))
                continue;

            if (!string.IsNullOrEmpty(search) &&
                !recipe.Name.Contains(search.Trim(), StringComparison.InvariantCultureIgnoreCase))
                continue;

            if (category != AllCategory)
            {
                if (category == FavoriteCategory && !_constructionSystem.Favorites.Contains(recipe))
                    continue;

                if (recipe.Category != category)
                    continue;
            }

            recipes.Add(recipe);
        }

        recipes.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.InvariantCulture));

        foreach (var recipe in recipes)
        {
            Recipes.Add(new ItemList.Item(Recipes)
            {
                Metadata = recipe,
                Text = recipe.Name,
                Icon = _spriteSystem.Frame0(recipe.Icon),
                TooltipEnabled = true,
                TooltipText = recipe.Description,
            });
        }
    }

    private void SelectRecipe(ItemList.ItemListSelectedEventArgs args)
    {
        var item = args.ItemList[args.ItemIndex];

        var prototype = (ConstructionPrototype)item.Metadata!;

        _selection = (prototype);

        SetRecipe(prototype);
    }

    private void DeselectRecipe()
    {
        _selection = null;

        ClearRecipe();
    }

    private void ClearRecipe()
    {
        BuildButton.Disabled = true;

        RecipeName.SetMessage(string.Empty);
        RecipeDescription.SetMessage(string.Empty);

        RecipeTexture.Texture = null;

        FavoriteButton.Visible = false;

        RecipeStepList.Clear();
    }

    private void SetRecipe(ConstructionPrototype recipe)
    {
        BuildButton.Disabled = false;
        BuildButton.Text = Loc.GetString(recipe.Type != ConstructionType.Item
            ? "construction-menu-place-ghost"
            : "construction-menu-craft");

        RecipeName.SetMessage(recipe.Name);
        RecipeDescription.SetMessage(recipe.Description);

        RecipeTexture.Texture = _spriteSystem.Frame0(recipe.Icon);

        FavoriteButton.Visible = true;
        FavoriteButton.Text = Loc.GetString(!_constructionSystem.Favorites.Contains(recipe)
            ? "construction-add-favorite-button"
            : "construction-remove-from-favorite-button");
    }

    private void DisableAll()
    {
        EraseButton.Pressed = false;
        BuildButton.Pressed = false;
    }

    private void Erase(BaseButton.ButtonToggledEventArgs args)
    {
        _constructionSystem.ToggleErase();

        EraseButton.Pressed = args.Pressed;
    }

    private void Build(BaseButton.ButtonToggledEventArgs args)
    {
        if (args.Pressed && _selection is not null)
        {
            if (_selection.Type == ConstructionType.Item)
            {
                _constructionSystem.TryStartItemConstruction(_selection);
                BuildButton.Pressed = false;
                return;
            }

            _constructionSystem.TryStartStructureConstruction(_selection);
        }
        else
            _constructionSystem.ClearPlacement();

        BuildButton.Pressed = args.Pressed;
    }
}
