using System.Linq;
using Content.Client.Construction;
using Content.Client.UserInterface.Controls;
using Content.Shared.Construction.Prototypes;
using Content.Shared.Whitelist;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Systems.Construction.Windows;

[GenerateTypedNameReferences]
public sealed partial class ConstructionWindow : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _systemManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    private readonly SpriteSystem _spriteSystem;
    private readonly EntityWhitelistSystem _whitelistSystem;

    private ConstructionSystem? _constructionSystem;

    private ConstructionPrototype? _selection;

    private readonly List<string> _categories;

    private const string FavoriteCategory = "construction-category-favorites";
    private const string AllCategory = "construction-category-all";

    public ConstructionWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _spriteSystem = _systemManager.GetEntitySystem<SpriteSystem>();
        _whitelistSystem = _systemManager.GetEntitySystem<EntityWhitelistSystem>();

        if (_systemManager.TryGetEntitySystem<ConstructionSystem>(out var constructionSystem))
            OnSystemLoaded(constructionSystem);

        _systemManager.SystemLoaded += (_, args) => OnSystemLoaded(args.System);
        _systemManager.SystemUnloaded += (_, args) => OnSystemUnloaded(args.System);

        _categories = GetCategories();

        BuildButton.OnToggled += Build;
        EraseButton.OnToggled += Erase;

        Recipes.OnItemSelected += SelectRecipe;
        Recipes.OnItemDeselected += _ => DeselectRecipe();

        FavoriteButton.OnPressed += _ => _constructionSystem?.ToggleFavorite(_selection);

        SearchBar.OnTextChanged += _ => PopulateRecipes(SearchBar.Text, _categories[OptionCategories.SelectedId]);
        OptionCategories.OnItemSelected += HandleSetCategory;

        ClearButton.OnPressed += _ => _constructionSystem?.ClearAllGhosts();

        PopulateCategories();
        PopulateRecipes(string.Empty, AllCategory);
    }

    private void RedrawSteps(object? sender, string constructionId)
    {
        if (_selection is null || _selection.ID != constructionId)
            return;

        SetRecipe(_selection);
    }

    private void HandleSetCategory(OptionButton.ItemSelectedEventArgs args)
    {
        OptionCategories.SelectId(args.Id);
        SearchBar.SetText(string.Empty);
        PopulateRecipes(string.Empty, _categories[args.Id]);
    }

    private List<string> GetCategories()
    {
        var categories = new HashSet<string>();

        foreach (var prototype in _prototypeManager.EnumeratePrototypes<ConstructionPrototype>())
        {
            var category = prototype.Category;

            if (!string.IsNullOrEmpty(category))
                categories.Add(category);
        }

        categories.Add(FavoriteCategory);
        categories.Add(AllCategory);

        return categories.OrderBy(Loc.GetString).ToList();
    }

    private void PopulateCategories()
    {
        OptionCategories.Clear();

        foreach (var category in _categories)
        {
            OptionCategories.AddItem(Loc.GetString(category));
        }
    }

    private void PopulateRecipes(string search, string category)
    {
        if (_constructionSystem is null)
            return;

        var recipes = new List<ConstructionPrototype>();

        Recipes.Clear();

        foreach (var recipe in _prototypeManager.EnumeratePrototypes<ConstructionPrototype>())
        {
            // Skip hidden recipes (e.g. mirrored recipes)
            if (recipe.Hide)
                continue;

            // Skip entity-locked recipes (e.g. arachnid's web buildings)
            if (_playerManager.LocalSession == null
                || _playerManager.LocalEntity == null
                || _whitelistSystem.IsWhitelistFail(recipe.EntityWhitelist, _playerManager.LocalEntity.Value))
                continue;

            if (!string.IsNullOrEmpty(search) &&
                !recipe.Name.Contains(search.Trim(), StringComparison.InvariantCultureIgnoreCase))
                continue;

            if (category != AllCategory)
            {
                if (category == FavoriteCategory && !_constructionSystem.Favorites.Contains(recipe))
                    continue;

                if (recipe.Category != category)
                    continue;
            }

            recipes.Add(recipe);
        }

        recipes.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.InvariantCulture));

        foreach (var recipe in recipes)
        {
            Recipes.Add(new ItemList.Item(Recipes)
            {
                Metadata = recipe,
                Text = recipe.Name,
                Icon = _spriteSystem.Frame0(recipe.Icon),
                TooltipEnabled = true,
                TooltipText = recipe.Description,
            });
        }
    }

    private void SelectRecipe(ItemList.ItemListSelectedEventArgs args)
    {
        var item = args.ItemList[args.ItemIndex];

        var prototype = (ConstructionPrototype)item.Metadata!;

        _selection = (prototype);

        SetRecipe(prototype);
    }

    private void DeselectRecipe()
    {
        _selection = null;

        ClearRecipe();
    }

    private void ClearRecipe()
    {
        BuildButton.Disabled = true;

        RecipeName.SetMessage(string.Empty);
        RecipeDescription.SetMessage(string.Empty);

        RecipeTexture.Texture = null;

        FavoriteButton.Visible = false;

        RecipeStepList.Clear();
    }

    private void SetRecipe(ConstructionPrototype recipe)
    {
        if (_constructionSystem is null)
            return;

        BuildButton.Disabled = false;
        BuildButton.Text = Loc.GetString(recipe.Type != ConstructionType.Item
            ? "construction-menu-place-ghost"
            : "construction-menu-craft");

        RecipeName.SetMessage(recipe.Name);
        RecipeDescription.SetMessage(recipe.Description);

        RecipeTexture.Texture = _spriteSystem.Frame0(recipe.Icon);

        FavoriteButton.Visible = true;
        FavoriteButton.Text = Loc.GetString(!_constructionSystem.Favorites.Contains(recipe)
            ? "construction-add-favorite-button"
            : "construction-remove-from-favorite-button");

        PopulateSteps(recipe, RecipeStepList);
    }

    /// <summary>
    /// Generates the step list for the recipe, and if not found, waits until the network sends it.
    /// </summary>
    private void PopulateSteps(ConstructionPrototype recipe, ItemList stepsList)
    {
        if (_constructionSystem is null)
            return;

        // If it's not in the cache, defer and wait for the event
        if (_constructionSystem.GetGuide(recipe) is not { } guide)
            return;

        foreach (var entry in guide.Entries)
        {
            var text = entry.Arguments is not null
                ? Loc.GetString(entry.Localization, entry.Arguments)
                : Loc.GetString(entry.Localization);

            if (entry.EntryNumber is { } number)
            {
                text = Loc.GetString("construction-presenter-step-wrapper",
                    ("step-number", number),
                    ("text", text));
            }

            var icon = entry.Icon != null
                ? _spriteSystem.Frame0(entry.Icon)
                : Texture.Transparent;

            stepsList.AddItem(text, icon, false);
        }
    }

    private void DisableAll(object? sender, EventArgs args)
    {
        EraseButton.Pressed = false;
        BuildButton.Pressed = false;
    }

    private void Erase(BaseButton.ButtonToggledEventArgs args)
    {
        if (_constructionSystem is null)
            return;

        _constructionSystem.ToggleErase();

        EraseButton.Pressed = args.Pressed;
    }

    private void Build(BaseButton.ButtonToggledEventArgs args)
    {
        if (_constructionSystem is null)
            return;

        if (args.Pressed && _selection is not null)
        {
            if (_selection.Type == ConstructionType.Item)
            {
                _constructionSystem.TryStartItemConstruction(_selection);
                BuildButton.Pressed = false;
                return;
            }

            _constructionSystem.TryStartStructureConstruction(_selection);
        }
        else
            _constructionSystem.ClearPlacement();

        BuildButton.Pressed = args.Pressed;
    }

    public void OnSystemLoaded(IEntitySystem sys)
    {
        if (sys is not ConstructionSystem system)
            return;

        _constructionSystem = system;

        _constructionSystem.PlacementChanged += DisableAll;
        _constructionSystem.ConstructionGuideReceived += RedrawSteps;

        // Make sure there's no old ghosts when loading the system.
        _constructionSystem.ClearAllGhosts();
    }

    private void OnSystemUnloaded(IEntitySystem sys)
    {
        if (sys is not ConstructionSystem system)
            return;

        if (system != _constructionSystem)
            return;

        if (_constructionSystem is null)
            throw new InvalidOperationException();

        _constructionSystem.PlacementChanged -= DisableAll;
        _constructionSystem.ConstructionGuideReceived -= RedrawSteps;

        _constructionSystem = null;
    }
}
