using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Replay.UI.Loading;

[GenerateTypedNameReferences]
public sealed partial class ReplayLoadingFailedControl : Control
{
    [Dependency] private IStylesheetManager _stylesheetManager = default!;
    private StylesheetManager.IStyleAccessor _accessor;


    public ReplayLoadingFailedControl(IStylesheetManager stylesheet)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _accessor = _stylesheetManager.GetStyleSubscription("System");

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _accessor.StyleChanged += OnStyleChanged;
    }

    protected override void ExitedTree()
    {
        _accessor.StyleChanged -= OnStyleChanged;

        base.ExitedTree();
    }

    private void OnStyleChanged(Stylesheet stylesheet, SheetletConfigRegistry configs)
    {
        Stylesheet = stylesheet;
    }

    public void SetData(Exception exception, Action? cancelPressed, Action? retryPressed)
    {
        ReasonLabel.SetMessage(
            FormattedMessage.FromUnformatted(Loc.GetString("replay-loading-failed", ("reason", exception))));

        if (cancelPressed != null)
        {
            CancelButton.Visible = true;
            CancelButton.OnPressed += _ =>
            {
                cancelPressed();
            };
        }

        if (retryPressed != null)
        {
            RetryButton.Visible = true;
            RetryButton.OnPressed += _ =>
            {
                retryPressed();
            };
        }
    }
}
